# Generated by Django 6.0.3 on 2026-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerprofile_created_at_playerprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
