# Generated by Django 6.0.3 on 2026-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
