# Generated by Django 6.0.3 on 2026-04-06 07:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coachprofile_availability_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[accounts.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.models.validate_phone_number]),
        ),
    ]
