# Generated by Django 6.0.3 on 2026-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
