--
-- PostgreSQL database dump
--

\restrict xk3PRiDo3BdrsIqQPyk1RSVYhnSdqQ7BDUYomxQgBmtGwJKOAgWckJ3tmlCWdcp

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_coachprofile; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.accounts_coachprofile (
    id bigint NOT NULL,
    image character varying(100),
    bio text NOT NULL,
    years_experience integer,
    coaching_level character varying(120) NOT NULL,
    specialties character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    availability_schedule jsonb NOT NULL,
    certifications jsonb NOT NULL,
    CONSTRAINT accounts_coachprofile_years_experience_check CHECK ((years_experience >= 0))
);


ALTER TABLE public.accounts_coachprofile OWNER TO coaching_user;

--
-- Name: accounts_coachprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.accounts_coachprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_coachprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_playerprofile; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.accounts_playerprofile (
    id bigint NOT NULL,
    age integer,
    preferred_foot character varying(10) NOT NULL,
    player_rating numeric(4,2) NOT NULL,
    primary_position character varying(50) NOT NULL,
    secondary_position character varying(50) NOT NULL,
    height_cm integer,
    weight_kg integer,
    user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    image character varying(100),
    emergency_contact_name character varying(150) NOT NULL,
    emergency_contact_phone character varying(20) NOT NULL,
    nationality character varying(100) NOT NULL,
    CONSTRAINT accounts_playerprofile_age_check CHECK ((age >= 0)),
    CONSTRAINT accounts_playerprofile_height_cm_check CHECK ((height_cm >= 0)),
    CONSTRAINT accounts_playerprofile_weight_kg_check CHECK ((weight_kg >= 0))
);


ALTER TABLE public.accounts_playerprofile OWNER TO coaching_user;

--
-- Name: accounts_playerprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.accounts_playerprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_playerprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone_number character varying(20),
    is_email_verified boolean NOT NULL,
    deleted_at timestamp with time zone
);


ALTER TABLE public.accounts_user OWNER TO coaching_user;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO coaching_user;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO coaching_user;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adminpanel_auditlog; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.adminpanel_auditlog (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    action character varying(10) NOT NULL,
    model_name character varying(100) NOT NULL,
    object_id character varying(255) NOT NULL,
    changes jsonb,
    summary character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.adminpanel_auditlog OWNER TO coaching_user;

--
-- Name: adminpanel_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.adminpanel_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adminpanel_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adminpanel_notification; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.adminpanel_notification (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    notification_type character varying(30) NOT NULL,
    link character varying(255) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    recipient_user_id bigint
);


ALTER TABLE public.adminpanel_notification OWNER TO coaching_user;

--
-- Name: adminpanel_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.adminpanel_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adminpanel_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO coaching_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO coaching_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO coaching_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_booking; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.bookings_booking (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    booked_at timestamp with time zone NOT NULL,
    player_id bigint NOT NULL,
    session_id bigint NOT NULL,
    cancellation_reason text NOT NULL
);


ALTER TABLE public.bookings_booking OWNER TO coaching_user;

--
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.bookings_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_payment; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.bookings_payment (
    id bigint NOT NULL,
    method character varying(10) NOT NULL,
    status character varying(10) NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    gateway_data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    booking_id bigint NOT NULL
);


ALTER TABLE public.bookings_payment OWNER TO coaching_user;

--
-- Name: bookings_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.bookings_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contents_testimonial; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.contents_testimonial (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    role character varying(20) NOT NULL,
    quote text NOT NULL,
    rating smallint NOT NULL,
    image character varying(100),
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT contents_testimonial_display_order_check CHECK ((display_order >= 0)),
    CONSTRAINT contents_testimonial_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.contents_testimonial OWNER TO coaching_user;

--
-- Name: contents_testimonial_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.contents_testimonial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contents_testimonial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO coaching_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO coaching_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO coaching_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO coaching_user;

--
-- Name: enquiries_enquiry; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.enquiries_enquiry (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    program_id bigint,
    admin_notes text NOT NULL,
    status character varying(20) NOT NULL
);


ALTER TABLE public.enquiries_enquiry OWNER TO coaching_user;

--
-- Name: enquiries_enquiry_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.enquiries_enquiry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enquiries_enquiry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_gallerycategory; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.gallery_gallerycategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(50) NOT NULL,
    description text NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT gallery_gallerycategory_display_order_check CHECK ((display_order >= 0))
);


ALTER TABLE public.gallery_gallerycategory OWNER TO coaching_user;

--
-- Name: gallery_gallerycategory_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.gallery_gallerycategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_gallerycategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_galleryitem; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.gallery_galleryitem (
    id bigint NOT NULL,
    media_type character varying(10) NOT NULL,
    image character varying(100),
    video_url character varying(200),
    thumbnail character varying(100),
    caption character varying(255) NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    video_file character varying(100),
    CONSTRAINT gallery_galleryitem_display_order_check CHECK ((display_order >= 0))
);


ALTER TABLE public.gallery_galleryitem OWNER TO coaching_user;

--
-- Name: gallery_galleryitem_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.gallery_galleryitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_galleryitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_trainingprogram; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.training_trainingprogram (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    session_type character varying(20) NOT NULL,
    default_duration_minutes integer NOT NULL,
    default_price numeric(8,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    display_order integer NOT NULL,
    hero_image character varying(100),
    short_description character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT training_trainingprogram_default_duration_minutes_check CHECK ((default_duration_minutes >= 0)),
    CONSTRAINT training_trainingprogram_display_order_check CHECK ((display_order >= 0))
);


ALTER TABLE public.training_trainingprogram OWNER TO coaching_user;

--
-- Name: training_trainingprogram_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.training_trainingprogram ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_trainingprogram_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_trainingsession; Type: TABLE; Schema: public; Owner: coaching_user
--

CREATE TABLE public.training_trainingsession (
    id bigint NOT NULL,
    session_date date,
    start_time time without time zone,
    end_time time without time zone,
    location character varying(255) NOT NULL,
    max_players integer NOT NULL,
    price numeric(8,2) NOT NULL,
    is_published boolean NOT NULL,
    is_cancelled boolean NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    coach_id bigint NOT NULL,
    program_id bigint NOT NULL,
    hero_image character varying(100),
    deleted_at timestamp with time zone,
    is_active boolean NOT NULL,
    CONSTRAINT training_trainingsession_max_players_check CHECK ((max_players >= 0))
);


ALTER TABLE public.training_trainingsession OWNER TO coaching_user;

--
-- Name: training_trainingsession_id_seq; Type: SEQUENCE; Schema: public; Owner: coaching_user
--

ALTER TABLE public.training_trainingsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_trainingsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_coachprofile; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.accounts_coachprofile (id, image, bio, years_experience, coaching_level, specialties, created_at, updated_at, user_id, availability_schedule, certifications) FROM stdin;
1	coaches/PP_iD6gSnK.jpg	Experienced Pro Licensed Coach/Manager	4	UEFA	Manager	2026-03-24 06:40:50.21796+00	2026-03-24 08:19:01.543481+00	3	{}	[]
3		Nostrud ipsum debiti	2017	Voluptate ex dolorem ducimus et	Quaerat soluta quo ullam impedit fugiat eum vero consectetur elit velit nostrum	2026-03-25 08:14:22.897586+00	2026-04-07 09:12:00.624922+00	8	{}	[]
\.


--
-- Data for Name: accounts_playerprofile; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.accounts_playerprofile (id, age, preferred_foot, player_rating, primary_position, secondary_position, height_cm, weight_kg, user_id, created_at, updated_at, image, emergency_contact_name, emergency_contact_phone, nationality) FROM stdin;
3	20	left	20.00	CAM	GK	160	60	5	2026-03-10 16:09:24.522507+00	2026-04-02 06:56:47.904946+00	players/PP_kC84sr1.jpg			
17	12	both	0.00	Cupidatat rerum non	Cupidatat rerum non	31	95	21	2026-03-13 15:20:55.531975+00	2026-03-13 15:20:55.531984+00				
18	66	left	0.00	Laudantium sit ill	Laudantium sit ill	61	51	22	2026-03-15 17:36:52.075844+00	2026-03-15 17:36:52.075852+00				
6	28	both	0.00	Facilis dolorum fugi	Facilis dolorum fugi	59	55	10	2026-03-13 11:46:16.04223+00	2026-03-16 08:42:32.446974+00				
35	98	right	0.00	Excepteur expedita s	Excepteur expedita s	45	89	41	2026-04-04 19:37:16.885794+00	2026-04-04 19:37:16.885807+00				
1	25	right	7.00			155	68	2	2026-03-09 07:14:11.822969+00	2026-04-04 21:23:01.377859+00	players/PP.jpg			
34	70	right	0.00	Magnam nesciunt eni	Magnam nesciunt eni	49	71	40	2026-04-04 19:34:17.406305+00	2026-04-05 14:10:05.838977+00				
19	31	left	0.00	Ut quia aut consequa	Ut quia aut consequa	100	64	23	2026-03-16 09:24:21.185132+00	2026-03-16 09:24:21.185141+00				
20	20	both	0.00	Rerum qui obcaecati	Rerum qui obcaecati	14	58	24	2026-03-16 09:32:50.413028+00	2026-03-16 09:32:50.413039+00	players/citizenship_back_jpg_1.jpg			
21	54	left	0.00	Rerum quibusdam cons	Rerum quibusdam cons	14	71	25	2026-03-17 10:58:51.600974+00	2026-03-17 10:58:51.600983+00				
22	31	both	0.00	In omnis aperiam rep	In omnis aperiam rep	7	14	26	2026-03-17 11:03:58.569018+00	2026-03-17 11:03:58.569026+00				
4	20	right	0.00	Midfielder	Striker	150	52	6	2026-03-10 16:38:27.000828+00	2026-03-18 08:11:36.310284+00	players/counterAttack.jfif			
36	77	both	0.00	Nisi quo deserunt in	Nisi quo deserunt in	68	42	42	2026-04-04 19:58:02.842576+00	2026-04-07 09:42:38.041882+00				
23	66	left	0.00	Consectetur fugiat	Consectetur fugiat	11	49	29	2026-03-25 09:06:34.843446+00	2026-03-25 09:06:34.843456+00				
24	5	both	0.00	Modi laboriosam per	Modi laboriosam per	97	69	30	2026-04-01 14:29:51.734017+00	2026-04-01 14:29:51.734025+00				
25	71	left	0.00	Ducimus aperiam vel	Ducimus aperiam vel	69	91	31	2026-04-01 14:39:06.851745+00	2026-04-01 14:39:06.851755+00				
26	87	both	0.00	Dolores dolores in t	Dolores dolores in t	71	11	32	2026-04-01 14:41:59.980659+00	2026-04-01 14:41:59.98067+00				
27	25	left	0.00	Vero beatae architec	Vero beatae architec	6	56	33	2026-04-01 14:43:02.468129+00	2026-04-01 14:43:02.468147+00				
28	70	left	0.00	Irure qui nisi volup	Irure qui nisi volup	27	18	34	2026-04-01 14:46:07.67867+00	2026-04-01 14:46:07.678679+00				
29	65	right	0.00	Velit deserunt odit	Velit deserunt odit	75	90	35	2026-04-01 14:47:38.684924+00	2026-04-01 14:47:38.684935+00				
30	28	both	0.00	Dolor voluptatem ali	Dolor voluptatem ali	45	58	36	2026-04-01 14:52:10.25147+00	2026-04-01 14:52:10.25148+00				
31	49	right	0.00	At dolor voluptas el	At dolor voluptas el	52	63	37	2026-04-01 14:52:35.026556+00	2026-04-01 14:52:35.026565+00				
32	66	left	0.00	Tenetur est quia qu	Tenetur est quia qu	92	13	38	2026-04-01 14:55:45.312192+00	2026-04-01 14:55:45.312201+00				
33	82	right	0.00	Voluptas aliquam in	Voluptas aliquam in	12	38	39	2026-04-01 14:56:15.93542+00	2026-04-01 14:56:15.935444+00				
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, phone_number, is_email_verified, deleted_at) FROM stdin;
10	pbkdf2_sha256$1200000$ioi1eCo16rrIuER8Q5Bjxw$XRtUi0kTMmqSSBd+IG5pM7Z7ySnZI/i+S8t+k5n+cOM=	\N	f	playertest	Oprah	Pacheco	kufypelef@mailinator.com	f	t	2026-03-13 11:46:15.532503+00	player	+1 (625) 296-1584	f	\N
27	pbkdf2_sha256$1200000$zP6q2kY8o6aYlZnzgu7o3t$VO+4kuiJSEY5X8q67sgQtNFf3xDm1lqL5KeByi0xznU=	\N	f	admin	admin	admin	admin@admin.com	f	t	2026-03-20 09:52:56.696585+00	admin	981234678	f	\N
4	pbkdf2_sha256$1200000$j4Qy3oSXCrxu2i9eIKfaU5$PshfH1wDad78++G8BhpXKQQ1fuO9zOAtwGVy5c36LA0=	\N	f	TestPlayer	Srijan	Pradhan	pradhansrijan07@gmail.com	f	t	2026-03-08 19:43:02+00	player	9861882504	f	\N
34	pbkdf2_sha256$1200000$NqPTu8ZhFW07H7TtE3f7K3$74lY5sXBTl2tjBb/EUPvV6TmFLbP2oHsWk25tY04F34=	\N	f	lareha	Serena	Finch	zonywusosi@mailinator.com	f	t	2026-04-01 14:45:58.699121+00	player	+1 (383) 956-7789	f	\N
35	pbkdf2_sha256$1200000$rDRBgV9fcz6LggvO0Q5x7O$R01cwt7+/yfFpAjYTyLTSWnyjLzVQkSXcxtE/Xl0hfU=	\N	f	xybilonu	Michael	Nolan	bugok@mailinator.com	f	t	2026-04-01 14:47:30.876088+00	player	+1 (129) 447-7603	f	\N
36	pbkdf2_sha256$1200000$ajwBVR1OQKlbaacNwZHjsF$5I/IsLNg81MQvVws8y7stUy6S8up12PZeTp6eoRhq8Q=	\N	f	jejucavog	Jasmine	Brennan	bolyku@mailinator.com	f	t	2026-04-01 14:52:02.41603+00	player	+1 (197) 982-2487	f	\N
23	pbkdf2_sha256$1200000$6PTSjrpoc8IXqwNyRMbTL8$6Gv8Z6bIzjHPp2OSyrh0srkDag3ACE4zjRK/RqE3l3U=	\N	f	bexogaw	Morgan	Frye	raxyhone@mailinator.com	f	t	2026-03-16 09:24:20.669362+00	player	+1 (274) 959-5745	f	\N
37	pbkdf2_sha256$1200000$QXYIqmGM28HVN60S81bqlu$daZrCT+X1utNI+FfZEe7VOS3Jakv7RiU1KskXTzuBzQ=	\N	f	kabyluwex	Charlotte	Vinson	xady@mailinator.com	f	t	2026-04-01 14:52:30.238767+00	player	+1 (848) 675-3063	f	\N
21	pbkdf2_sha256$1200000$00F5HL4tv6eIF8pJO2ABaD$rHNCxduYZt6crdnUoPffu79KaCLJO5tQ8urJVb2HX20=	\N	f	player3	Caldwell	Wolf	fabov@mailinator.com	f	t	2026-03-13 15:20:54.989989+00	player	+1 (237) 345-9304	f	\N
38	pbkdf2_sha256$1200000$jP8IxITrAR3bI6avt92tiM$IpdE0oVAqpbHkkdNs4LxfloS/NUeM1M48nHCvWOLvPo=	\N	f	jeducaz	Channing	Payne	kozar@mailinator.com	f	t	2026-04-01 14:55:40.689603+00	player	+1 (146) 903-6341	f	\N
22	pbkdf2_sha256$1200000$AmoubtUYrcMN0cOBwBleJb$H77Ou5iBebUn2aiGFYOaNwhzG3mNud442eP1iXyiJLM=	\N	f	nucefysab	Rahim	Allison	dizusul@mailinator.com	f	t	2026-03-15 17:36:51.543655+00	player	+1 (656) 854-7302	f	\N
24	pbkdf2_sha256$1200000$uDgJv8BR7rKLfzYfboXI0s$FJ0JvLM1My9f0bBRFvm/BW4ONrHoht3ICgwth0xFulY=	\N	f	gazumety	Hu	Dorsey	fybix@mailinator.com	f	t	2026-03-16 09:32:49.924171+00	player	+1 (972) 628-3562	f	\N
39	pbkdf2_sha256$1200000$prt3uVa3X8CNeQBCKZyKJK$P1YRqWNHDZ9yCZHcW3JNIKZ1cYRP49DNmzdfafHT5g0=	\N	f	homyxo	Charlotte	Dillard	jiwijydec@mailinator.com	f	t	2026-04-01 14:56:07.580083+00	player	+1 (818) 875-9373	f	\N
8	pbkdf2_sha256$1200000$kt9B8EDWkcE51kmz8xWklx$6LhBosPIdt2QVbLM1NLkYdDVVozeS+1wxRm84ZMPpUc=	\N	f	sanjeevstha	Sanjeev	Shrestha	sanjeev@gmail.com	f	t	2026-03-11 17:36:37+00	coach	9846548412	f	\N
5	pbkdf2_sha256$1200000$h2urLEGPki03epnOznHZa1$QuDHuLqGVwVejvLeF2R5Dxba4GRc/BaahPM5ixL0en4=	\N	f	player1	player	one	player1@gmail.com	f	t	2026-03-10 16:09:24+00	player	9800000000	f	\N
26	pbkdf2_sha256$1200000$YsERfcGbIjoSAUdIMYh5hc$XgiKe6asD3qR5g4vzqChESqTFXi8SqTTcf0skja9Lr4=	\N	f	baqorenuno	Lalalalalalala	Mcintosh	jerige@mailinator.com	f	f	2026-03-17 11:03:58.068809+00	player	+1 (401) 262-7119	f	\N
25	pbkdf2_sha256$1200000$WzFmnOhKtG2syCjEhbEjuY$qU/CjJoCEnOr9lk2/SUz6gD4SDslZ5zOhM1E8UEqtS8=	\N	f	zofejew	Lucas	Oneil	biqi@mailinator.com	f	f	2026-03-17 10:58:51.093344+00	player	+1 (585) 771-3017	f	\N
6	pbkdf2_sha256$1200000$CxlyT5ZgBRiRt9ROsZEDNG$RhPpMxokiOyUSm9fHZpERnbsVAK3d6fjl5PWkRTxDaU=	\N	f	player2	Player	Two	playertwo@gmail.com	f	t	2026-03-10 16:38:26.498335+00	player	981234569	f	\N
40	pbkdf2_sha256$1200000$BLVMohx8qI65QDY6BgFsWP$aiQ3iHrukEFRpDPr0yCpxt6zhX3n7wWoAMIJ8KblnAo=	\N	f	playertest1	Knoxa	Hancock	pezadikyqo@mailinator.com	f	t	2026-04-04 19:34:08.683036+00	player	+1 (335) 248-4283	f	\N
1	pbkdf2_sha256$1200000$ZPtTk9SDTVB9qJ7bP1liL8$5a3Of6iyAnwUPeUKdYxWy96n554gxKV3Z0DwuzYqxCY=	2026-04-05 19:29:35.66337+00	t	root				t	t	2026-03-08 19:29:11+00	admin	\N	f	\N
42	pbkdf2_sha256$1200000$pjEyOu9ZycVXGCtcbWON5x$2CtGzoGNvQetDHv09uJZYHal5zPoGiMkXN1BRQw8SH8=	\N	f	playertest3	Ferrissss	Franklin	bopun@mailinator.com	f	t	2026-04-04 19:57:53.07219+00	player	+1 (673) 774-3803	f	\N
3	pbkdf2_sha256$1200000$bbBMj73v3I6RaFrmKCdVCo$RUBTVsWw9JQjlQcfhtXlvzX1t6f8WCSp682z8LOhLYg=	\N	f	testcoach	Srijan	Pradhan	pradhansrijan07@gmail.com	f	t	2026-03-08 19:34:21.333178+00	coach	9861882503	f	\N
41	pbkdf2_sha256$1200000$4fARJDp2jsea5MXSdXfeqQ$nG5Dnq5uyBtWGJ0iNo4h9i6Crm7/kdZqlimUzj/Z1X0=	\N	f	playertest2	Barbara	Hicks	mujinec@mailinator.com	f	t	2026-04-04 19:37:08.831628+00	player	+1 (536) 161-2509	f	\N
28	pbkdf2_sha256$1200000$URW3YHJ7FXqpNtNhPWFPTA$8887Ofow/wSY4NZn3nM1ncfWAqtuJQiRF8divf9U/+g=	\N	f	zykah	Ivor	Fernandez	moxytopazy@mailinator.com	f	t	2026-03-25 09:06:07.82596+00	player	+1 (939) 987-8939	f	\N
29	pbkdf2_sha256$1200000$jlc7hmgvol0X9mP7aRT9AR$XbkWjHWHnaI835In9UFqpogWc6hA4nR3dUkgRvPh4nE=	\N	f	vyvypejeji	Althea	Hodges	sunuxuxu@mailinator.com	f	t	2026-03-25 09:06:34.347484+00	player	+1 (204) 301-2938	f	\N
30	pbkdf2_sha256$1200000$zjaWVpZmpNx9vFynNJZa4h$XFBmsfCeh1IX9mIVUl9tijI0ZnYnxsHU2hBOQPTZYqE=	\N	f	dofigoga	Shelby	Phelps	zare@mailinator.com	f	t	2026-04-01 14:29:51.219236+00	player	+1 (924) 741-7699	f	\N
31	pbkdf2_sha256$1200000$8fmB5ikTuNuNsTOwCfLklq$/O3nf++2iLzdfo2jZkUXWdWA3MRyOloWntoE0StB+eo=	\N	f	kogojogu	Veda	Foley	cyzixidas@mailinator.com	f	t	2026-04-01 14:39:06.343139+00	player	+1 (617) 407-2413	f	\N
32	pbkdf2_sha256$1200000$qS9PxipUbFlY0I8jh2FSXC$kWMHbAb7ESfEvT9uKRx7nOyEkoRMYKnBRDyyuylG6ZU=	\N	f	cawoxetobi	Zelenia	Blake	nubykoji@mailinator.com	f	t	2026-04-01 14:41:59.456786+00	player	+1 (923) 633-2482	f	\N
33	pbkdf2_sha256$1200000$zDHf93GzsTa6HLz92qBM6I$h2deLMgWpHGqflLz/naWc65xxV2Y5S0PL/5hE6TWaVw=	\N	f	bidylyzo	Cynthia	Turner	xobymemoj@mailinator.com	f	t	2026-04-01 14:43:01.936387+00	player	+1 (651) 501-3956	f	\N
2	pbkdf2_sha256$1200000$3CLcus63lsUlId1YYO5EbT$JCto6hGb0M/mmfOXcsCq97rJbHiHv2E42Cp9h0eUIw0=	\N	f	srijanpradhan	Srijan	Pradhan	pradhansrijan07@gmail.com	f	t	2026-03-08 19:31:11.349251+00	player	9861882503	t	\N
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: adminpanel_auditlog; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.adminpanel_auditlog (id, "timestamp", action, model_name, object_id, changes, summary, user_id) FROM stdin;
1	2026-04-07 06:28:29.029925+00	update	User	42	{"password": {"new": "pbkdf2_sha256$1200000$pjEyOu9ZycVXGCtcbWON5x$2CtGzoGNvQetDHv09uJZYHal5zPoGiMkXN1BRQw8SH8=", "old": null}, "is_active": {"new": true, "old": false}}	Changed User #42	\N
2	2026-04-07 06:28:50.726667+00	update	Booking	bulk	{"action": "status_update to pending", "affected_count": 1}	Bulk status_update to pending on 1 Booking(s)	\N
3	2026-04-07 06:33:15.373911+00	delete	Booking	24	\N	Deleted Booking #24	\N
4	2026-04-07 08:36:26.532024+00	create	GalleryItem	8	\N	Added a new gallery item (#8)	1
5	2026-04-07 08:44:50.563415+00	update	User	42	{"password": {"new": "pbkdf2_sha256$1200000$pjEyOu9ZycVXGCtcbWON5x$2CtGzoGNvQetDHv09uJZYHal5zPoGiMkXN1BRQw8SH8=", "old": null}, "is_active": {"new": false, "old": true}}	Changed password, is active on user account	1
6	2026-04-07 08:45:12.658298+00	update	User	42	{"password": {"new": "pbkdf2_sha256$1200000$pjEyOu9ZycVXGCtcbWON5x$2CtGzoGNvQetDHv09uJZYHal5zPoGiMkXN1BRQw8SH8=", "old": null}, "is_active": {"new": true, "old": false}}	Changed password, is active on user account	1
7	2026-04-07 08:45:30.548965+00	delete	TrainingProgram	9	\N	Removed training program #9	1
8	2026-04-07 08:50:14.950273+00	update	Enquiry	bulk	{"action": "status_update to closed", "affected_count": 9}	Status Update To Closed 9 Enquirys	1
9	2026-04-07 08:50:36.559022+00	update	User	42	{"password": {"new": "pbkdf2_sha256$1200000$pjEyOu9ZycVXGCtcbWON5x$2CtGzoGNvQetDHv09uJZYHal5zPoGiMkXN1BRQw8SH8=", "old": null}, "is_active": {"new": false, "old": true}}	Changed password, is active on user account	1
10	2026-04-07 08:53:29.937866+00	delete	GalleryItem	8	\N	Removed gallery item #8	1
11	2026-04-07 08:53:38.523028+00	delete	GalleryItem	6	\N	Removed gallery item #6	1
12	2026-04-07 08:55:51.983396+00	update	User	42	{"is_active": {"new": true, "old": false}}	Changed is active on user account	1
13	2026-04-07 08:56:34.15124+00	create	TrainingProgram	11	\N	Added a new training program: Atque officiis inven	1
14	2026-04-07 08:56:50.842655+00	delete	TrainingProgram	11	\N	Removed training program: Atque officiis inven	1
15	2026-04-07 08:57:31.942171+00	update	Enquiry	bulk	{"action": "status_update to new", "affected_count": 9}	Changed status to 'new' on 9 enquirys	1
16	2026-04-07 09:00:08.188817+00	delete	GalleryItem	7	\N	Removed gallery item: #7	1
17	2026-04-07 09:08:18.323589+00	update	User	42	{"is_active": {"new": false, "old": true}}	Changed is active on user account	1
18	2026-04-07 09:09:17.824293+00	create	GalleryItem	9	\N	Added a new gallery item: #9	1
19	2026-04-07 09:10:23.077832+00	update	Booking	42	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking	1
20	2026-04-07 09:10:23.081426+00	update	Booking	42	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking #42	1
21	2026-04-07 09:11:02.113697+00	update	Enquiry	bulk	{"action": "status_update to contacted", "affected_count": 9}	Changed status to 'contacted' on 9 enquirys	1
22	2026-04-07 09:11:21.684851+00	update	Booking	bulk	{"action": "status_update to pending", "affected_count": 3}	Changed status to 'pending' on 3 bookings	1
23	2026-04-07 09:11:47.108538+00	create	GalleryItem	10	\N	Added a new gallery item: #10	1
24	2026-04-07 09:11:57.024964+00	update	User	8	{"is_active": {"new": false, "old": true}}	Changed is active on user account	1
25	2026-04-07 09:12:00.622051+00	update	User	8	{"is_active": {"new": true, "old": false}}	Changed is active on user account	1
26	2026-04-07 09:21:20.447694+00	update	Enquiry	bulk	{"action": "status_update to new", "affected_count": 1}	Changed status to 'new' on 1 enquiry	1
27	2026-04-07 09:42:38.039235+00	update	User	42	{"is_active": {"new": true, "old": false}}	Changed is active on user account	1
28	2026-04-07 10:10:57.867372+00	update	Booking	42	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking	1
29	2026-04-07 10:10:57.874217+00	update	Booking	42	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking #42	1
30	2026-04-07 10:12:23.211966+00	update	Enquiry	41	{"status": {"new": "contacted", "old": "new"}}	Changed status on enquiry	1
31	2026-04-07 10:17:43.35739+00	delete	TrainingSession	18	\N	Removed training session: #18	1
32	2026-04-07 10:24:39.858084+00	delete	GalleryItem	10	\N	Removed gallery item: #10	1
33	2026-04-07 10:30:53.937533+00	delete	TrainingSession	15	\N	Removed training session: #15	1
34	2026-04-07 10:32:24.751402+00	delete	TrainingSession	11	\N	Removed training session: #11	1
35	2026-04-07 10:41:53.737857+00	create	TrainingProgram	12	\N	Added a new training program: Sunt voluptate eum s	1
36	2026-04-07 10:42:35.743196+00	delete	Booking	25	\N	Removed booking: #25	1
37	2026-04-07 10:48:24.844843+00	delete	Booking	42	\N	Removed booking: #42	1
38	2026-04-07 10:48:24.845788+00	delete	Booking	41	\N	Removed booking: #41	1
39	2026-04-07 10:48:24.849407+00	delete	Booking	bulk	{"action": "delete", "affected_count": 4}	Removed 4 bookings in bulk	1
40	2026-04-07 10:48:47.940485+00	delete	TrainingSession	bulk	{"action": "delete", "affected_count": 1}	Removed 1 training session in bulk	1
41	2026-04-07 11:47:09.80699+00	create	Booking	43	\N	Added a new booking: #43	2
42	2026-04-07 11:47:20.272439+00	create	Booking	44	\N	Added a new booking: #44	2
43	2026-04-07 11:47:28.959903+00	update	Booking	44	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking	1
44	2026-04-07 11:47:28.963076+00	update	Booking	44	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking #44	1
45	2026-04-07 11:47:29.981043+00	update	Booking	43	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking	1
46	2026-04-07 11:47:29.984177+00	update	Booking	43	{"status": {"new": "confirmed", "old": "pending"}}	Changed status on booking #43	1
\.


--
-- Data for Name: adminpanel_notification; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.adminpanel_notification (id, title, message, notification_type, link, is_read, created_at, recipient_user_id) FROM stdin;
1	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-01 14:26:45.635248+00	\N
2	New player registered: Shelby Phelps	@dofigoga just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:29:51.727452+00	\N
6	New enquiry from Maite Reese	Velit voluptate dolo	enquiry	/admin-dashboard/enquiries	t	2026-04-01 14:34:32.609598+00	\N
3	New enquiry from David Pollard	Error libero sit nih	enquiry	/admin-dashboard/enquiries	t	2026-04-01 14:30:23.115013+00	\N
4	New enquiry from TaShya Franco	Possimus labore ull	enquiry	/admin-dashboard/enquiries	t	2026-04-01 14:33:14.60864+00	\N
5	New enquiry from Madonna Padilla	Vitae quis dolorem e	enquiry	/admin-dashboard/enquiries	t	2026-04-01 14:33:49.057172+00	\N
7	New player registered: Veda Foley	@kogojogu just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:39:06.845884+00	\N
8	New player registered: Zelenia Blake	@cawoxetobi just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:41:59.975727+00	\N
9	New player registered: Cynthia Turner	@bidylyzo just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:43:02.462732+00	\N
10	New player registered: Serena Finch	@lareha just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:45:59.222512+00	\N
11	New player registered: Michael Nolan	@xybilonu just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:47:31.413033+00	\N
12	New player registered: Jasmine Brennan	@jejucavog just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:52:02.925851+00	\N
13	New player registered: Charlotte Vinson	@kabyluwex just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:52:30.778177+00	\N
14	New player registered: Channing Payne	@jeducaz just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:55:41.211356+00	\N
15	New player registered: Charlotte Dillard	@homyxo just joined the academy.	registration	/admin-dashboard/players	t	2026-04-01 14:56:08.093128+00	\N
16	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-01 14:56:27.048967+00	\N
22	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-05 14:20:26.739309+00	\N
17	New player registered: Knox Hancock	@playertest1 just joined the academy.	registration	/admin-dashboard/players	t	2026-04-04 19:34:09.212881+00	\N
18	New booking: Knox Hancock	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-04 19:34:47.339973+00	\N
19	New player registered: Barbara Hicks	@playertest2 just joined the academy.	registration	/admin-dashboard/players	t	2026-04-04 19:37:09.35667+00	\N
20	New player registered: Ferris Franklin	@playertest3 just joined the academy.	registration	/admin-dashboard/players	t	2026-04-04 19:57:53.600342+00	\N
21	Booking cancelled: Knox Hancock	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-05 13:56:47.123879+00	\N
23	Booking cancelled: Srijan Pradhan	Goalkeeping Masterclass on 2026-12-01	cancellation	/admin-dashboard/bookings	t	2026-04-05 19:23:53.926689+00	\N
24	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-11-24	cancellation	/admin-dashboard/bookings	t	2026-04-05 19:23:57.463808+00	\N
25	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-05 19:24:02.938949+00	\N
26	New booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-11-24	booking	/admin-dashboard/bookings	t	2026-04-05 19:47:26.498597+00	\N
27	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:31:55.064912+00	\N
28	Re-booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-06 05:32:44.998921+00	\N
29	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:32:57.372752+00	\N
30	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-11-24	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:39:06.820603+00	\N
31	Re-booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-06 05:41:53.689558+00	\N
32	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:42:15.834234+00	\N
33	Re-booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-06 05:42:48.140511+00	\N
34	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:42:56.557642+00	\N
35	Re-booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-06 05:45:18.099513+00	\N
36	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:45:31.317779+00	\N
37	New booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-06 05:49:08.052198+00	\N
38	Booking cancelled: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:49:23.494194+00	\N
39	Booking cancelled: player one	Corner Kick Mastery on 2026-12-20	cancellation	/admin-dashboard/bookings	t	2026-04-06 05:51:18.232627+00	\N
40	Re-booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	t	2026-04-06 09:28:44.531988+00	\N
41	New booking: Srijan Pradhan	Counter Attacking Masterclass on 2027-03-24	booking	/admin-dashboard/bookings	t	2026-04-06 09:48:38.629485+00	\N
42	New booking: Srijan Pradhan	Counter Attacking Masterclass on 2026-10-14	booking	/admin-dashboard/bookings	f	2026-04-07 11:47:05.151648+00	\N
43	New booking: Srijan Pradhan	Corner Kick Mastery on 2026-12-20	booking	/admin-dashboard/bookings	f	2026-04-07 11:47:15.83073+00	\N
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	7	add_user
22	Can change user	7	change_user
23	Can delete user	7	delete_user
24	Can view user	7	view_user
25	Can add player profile	6	add_playerprofile
26	Can change player profile	6	change_playerprofile
27	Can delete player profile	6	delete_playerprofile
28	Can view player profile	6	view_playerprofile
29	Can add training program	8	add_trainingprogram
30	Can change training program	8	change_trainingprogram
31	Can delete training program	8	delete_trainingprogram
32	Can view training program	8	view_trainingprogram
33	Can add training session	9	add_trainingsession
34	Can change training session	9	change_trainingsession
35	Can delete training session	9	delete_trainingsession
36	Can view training session	9	view_trainingsession
37	Can add booking	10	add_booking
38	Can change booking	10	change_booking
39	Can delete booking	10	delete_booking
40	Can view booking	10	view_booking
41	Can add coach	11	add_coach
42	Can change coach	11	change_coach
43	Can delete coach	11	delete_coach
44	Can view coach	11	view_coach
45	Can add enquiry	12	add_enquiry
46	Can change enquiry	12	change_enquiry
47	Can delete enquiry	12	delete_enquiry
48	Can view enquiry	12	view_enquiry
49	Can add testimonial	13	add_testimonial
50	Can change testimonial	13	change_testimonial
51	Can delete testimonial	13	delete_testimonial
52	Can view testimonial	13	view_testimonial
53	Can add coach profile	14	add_coachprofile
54	Can change coach profile	14	change_coachprofile
55	Can delete coach profile	14	delete_coachprofile
56	Can view coach profile	14	view_coachprofile
57	Can add notification	15	add_notification
58	Can change notification	15	change_notification
59	Can delete notification	15	delete_notification
60	Can view notification	15	view_notification
61	Can add Gallery Category	16	add_gallerycategory
62	Can change Gallery Category	16	change_gallerycategory
63	Can delete Gallery Category	16	delete_gallerycategory
64	Can view Gallery Category	16	view_gallerycategory
65	Can add Gallery Item	17	add_galleryitem
66	Can change Gallery Item	17	change_galleryitem
67	Can delete Gallery Item	17	delete_galleryitem
68	Can view Gallery Item	17	view_galleryitem
69	Can add payment	18	add_payment
70	Can change payment	18	change_payment
71	Can delete payment	18	delete_payment
72	Can view payment	18	view_payment
73	Can add audit log	19	add_auditlog
74	Can change audit log	19	change_auditlog
75	Can delete audit log	19	delete_auditlog
76	Can view audit log	19	view_auditlog
\.


--
-- Data for Name: bookings_booking; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.bookings_booking (id, status, booked_at, player_id, session_id, cancellation_reason) FROM stdin;
44	confirmed	2026-04-07 11:47:15.829617+00	1	10	
43	confirmed	2026-04-07 11:47:05.141266+00	1	13	
\.


--
-- Data for Name: bookings_payment; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.bookings_payment (id, method, status, amount, transaction_id, gateway_data, created_at, updated_at, booking_id) FROM stdin;
10	cash	completed	500.00		{}	2026-04-07 11:47:20.27361+00	2026-04-07 11:47:28.957917+00	44
9	cash	completed	323.00		{}	2026-04-07 11:47:09.809038+00	2026-04-07 11:47:29.979+00	43
\.


--
-- Data for Name: contents_testimonial; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.contents_testimonial (id, name, role, quote, rating, image, display_order, is_active, created_at) FROM stdin;
1	Ronan Wooten	player	Beatae deleniti cons	5		25	t	2026-03-12 11:02:37.74574+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-03-08 19:31:11.829734+00	2	srijanpradhan (player)	1	[{"added": {}}]	7	1
2	2026-03-08 19:31:48.082621+00	1	root (admin)	2	[{"changed": {"fields": ["Role"]}}]	7	1
3	2026-03-08 19:32:37.756529+00	1	PlayerProfile - srijanpradhan	1	[{"added": {}}]	6	1
4	2026-03-08 19:34:21.814019+00	3	TestCoach (coach)	1	[{"added": {}}]	7	1
5	2026-03-08 19:43:02.545263+00	4	TestPlayer (player)	1	[{"added": {}}]	7	1
6	2026-03-09 09:01:21.151591+00	1	1v1 Defending Masterclass	1	[{"added": {}}]	8	1
7	2026-03-09 09:03:13.03761+00	1	1v1 Defending Masterclass - 2026-03-10 06:00:00	1	[{"added": {}}]	9	1
8	2026-03-09 09:04:12.04494+00	1	srijanpradhan -> 1v1 Defending Masterclass - 2026-03-10 06:00:00	1	[{"added": {}}]	10	1
9	2026-03-09 09:14:37.534536+00	1	Srijan -> 1v1 Defending Masterclass - 2026-03-10 06:00:00	3		10	1
10	2026-03-09 09:21:53.896711+00	2	srijanpradhan -> 1v1 Defending Masterclass - 2026-03-10 06:00:00	1	[{"added": {}}]	10	1
11	2026-03-09 09:25:24.314305+00	4	Srijan Pradhan (player)	2	[{"changed": {"fields": ["Phone number"]}}]	7	1
12	2026-03-09 09:26:32.047036+00	2	Player - Srijan Pradhan	1	[{"added": {}}]	6	1
13	2026-03-09 09:27:17.806361+00	2	Player - Srijan Pradhan	3		6	1
14	2026-03-10 16:17:39.540525+00	2	Counter Attacking Masterclass	1	[{"added": {}}]	8	1
15	2026-03-10 16:17:46.488932+00	1	Counter Attacking Masterclass - 2026-03-10 06:00:00	2	[{"changed": {"fields": ["Program", "Max players"]}}]	9	1
16	2026-03-10 16:22:57.1744+00	2	1v1 Defending Masterclass - 2026-03-10 06:00:00	1	[{"added": {}}]	9	1
17	2026-03-11 07:36:24.265065+00	5	 Player - player one	2	[{"changed": {"fields": ["First name", "Last name"]}}]	7	1
18	2026-03-11 07:39:52.851172+00	7	 Player - Player Three	1	[{"added": {}}]	7	1
19	2026-03-11 08:26:11.560683+00	1	Srijan Pradhan	1	[{"added": {}}]	11	1
20	2026-03-11 08:27:37.119485+00	1	Srijan Pradhan	2	[{"changed": {"fields": ["Image"]}}]	11	1
21	2026-03-11 08:27:50.506662+00	1	Srijan Pradhan	2	[{"changed": {"fields": ["Image"]}}]	11	1
22	2026-03-11 08:34:54.539251+00	1	Srijan Pradhan	2	[{"changed": {"fields": ["Image"]}}]	11	1
23	2026-03-11 08:35:01.68671+00	1	Srijan Pradhan	2	[{"changed": {"fields": ["Image"]}}]	11	1
24	2026-03-11 08:39:56.361215+00	1	Player - Srijan Pradhan	2	[{"changed": {"fields": ["Image"]}}]	6	1
25	2026-03-11 10:22:23.512872+00	1	Counter Attacking Masterclass - 2026-05-30 06:00:00	2	[{"changed": {"fields": ["Session date"]}}]	9	1
26	2026-03-11 10:22:38.21868+00	2	1v1 Defending Masterclass - 2026-06-30 06:00:00	2	[{"changed": {"fields": ["Session date"]}}]	9	1
27	2026-03-11 10:30:44.104382+00	1	1v1 Defending Masterclass	2	[{"changed": {"fields": ["Hero image"]}}]	8	1
28	2026-03-11 17:36:02.881335+00	3	Goalkeeping Masterclass	1	[{"added": {}}]	8	1
29	2026-03-11 17:36:37.81675+00	8	 Coach - Sanjeev Shrestha	1	[{"added": {}}]	7	1
30	2026-03-11 17:37:05.491908+00	3	Goalkeeping Masterclass - 2026-03-25 06:00:00	1	[{"added": {}}]	9	1
31	2026-03-11 20:13:30.213339+00	6	player2 -> Counter Attacking Masterclass - 2026-05-30 06:00:00	2	[{"changed": {"fields": ["Status"]}}]	10	1
32	2026-03-12 10:44:06.828114+00	1	Parent One - Counter Attacking Masterclass	1	[{"added": {}}]	12	1
33	2026-03-12 11:02:37.747262+00	1	Ronan Wooten (Player)	1	[{"added": {}}]	13	1
34	2026-03-12 11:02:45.018217+00	1	Ronan Wooten (Player)	2	[{"changed": {"fields": ["Is active"]}}]	13	1
35	2026-03-13 11:36:39.479199+00	9	 Player - Player Three	3		7	1
36	2026-03-13 11:49:14.33535+00	11	 Player - Levi Guzman	3		7	1
37	2026-03-13 11:55:19.766008+00	12	 Player - Emerson Maynard	3		7	1
38	2026-03-13 11:57:24.972005+00	13	 Player - Hedley Rogers	3		7	1
39	2026-03-13 12:02:50.340016+00	14	 Player - Zachery Phelps	3		7	1
40	2026-03-13 12:03:38.865886+00	15	 Player - Emery Hahn	3		7	1
41	2026-03-13 12:09:17.92182+00	16	 Player - Ira Phelps	3		7	1
42	2026-03-13 14:52:39.233985+00	17	 Player - Rajah Combs	3		7	1
43	2026-03-13 14:52:39.234021+00	18	 Player - Amanda Kemp	3		7	1
44	2026-03-13 14:52:55.849174+00	7	 Player - Player Three	3		7	1
45	2026-03-13 15:20:45.171725+00	19	 Player - Lois Branch	3		7	1
46	2026-03-13 15:20:45.171759+00	20	 Player - Daria Gomez	3		7	1
47	2026-03-13 15:29:16.026665+00	21	 Player - Caldwell Wolf	2	[{"changed": {"fields": ["password"]}}]	7	1
48	2026-03-14 15:47:56.114696+00	6	 Player - Player Two	2	[{"changed": {"fields": ["password"]}}]	7	1
49	2026-03-15 17:12:59.435219+00	4	Counter Attacking Masterclass - 2026-05-30 06:00:00	1	[{"added": {}}]	9	1
50	2026-03-15 17:29:45.561409+00	4	Beginners Program	1	[{"added": {}}]	8	1
51	2026-03-15 18:21:54.006209+00	5	Goalkeeping Masterclass - None None	1	[{"added": {}}]	9	1
52	2026-03-15 18:22:50.854945+00	5	Goalkeeping Masterclass - 2026-06-30 None	2	[{"changed": {"fields": ["Session date"]}}]	9	1
53	2026-03-15 18:23:12.628432+00	5	Goalkeeping Masterclass - 2026-06-30 06:00:00	2	[{"changed": {"fields": ["Start time", "End time"]}}]	9	1
54	2026-03-15 18:23:41.986671+00	4	Counter Attacking Masterclass - 2026-05-30 06:00:00	3		9	1
55	2026-03-15 18:25:37.282641+00	3	Goalkeeping Masterclass - 2026-03-25 06:00:00	3		9	1
56	2026-03-15 18:26:16.169818+00	6	Goalkeeping Masterclass - None None	1	[{"added": {}}]	9	1
57	2026-03-15 18:26:29.603305+00	6	Goalkeeping Masterclass - None None	2	[]	9	1
58	2026-03-15 18:26:34.532069+00	2	1v1 Defending Masterclass - 2026-06-30 06:00:00	2	[]	9	1
59	2026-03-15 18:26:47.703998+00	5	Goalkeeping Masterclass - 2026-06-30 06:00:00	2	[{"changed": {"fields": ["Is published", "Is cancelled"]}}]	9	1
60	2026-03-15 18:27:06.359732+00	6	Goalkeeping Masterclass - 2026-03-25 None	2	[{"changed": {"fields": ["Session date"]}}]	9	1
61	2026-03-15 18:33:19.848875+00	6	Goalkeeping Masterclass - 2026-03-25 None	2	[{"changed": {"fields": ["Hero image"]}}]	9	1
62	2026-03-15 18:34:35.576105+00	1	Counter Attacking Masterclass - 2026-05-30 06:00:00	2	[{"changed": {"fields": ["Hero image"]}}]	9	1
63	2026-03-15 18:35:41.23097+00	2	1v1 Defending Masterclass - 2026-06-30 06:00:00	2	[{"changed": {"fields": ["Hero image"]}}]	9	1
64	2026-03-16 06:34:25.251254+00	6	Goalkeeping Masterclass - 2026-03-25 06:00:00	2	[{"changed": {"fields": ["Start time", "End time", "Location"]}}]	9	1
65	2026-03-16 07:43:19.576308+00	3	Player - player one	2	[{"changed": {"fields": ["Image"]}}]	6	1
66	2026-03-19 04:16:08.475615+00	2	 Player - Srijan Pradhan	2	[{"changed": {"fields": ["password"]}}]	7	1
67	2026-03-20 09:52:57.23867+00	27	Admin - admin admin	1	[{"added": {}}]	7	1
68	2026-03-24 06:40:50.225424+00	1	Coach - Srijan Pradhan	1	[{"added": {}}]	14	1
69	2026-03-24 06:57:44.4622+00	2	Coach - Sanjeev Shrestha	3		14	1
70	2026-03-24 07:08:39.598867+00	8	Admin - Sanjeev Shrestha	2	[{"changed": {"fields": ["Role"]}}]	7	1
71	2026-03-24 07:11:08.376288+00	8	Coach - Sanjeev Shrestha	2	[{"changed": {"fields": ["Role"]}}]	7	1
72	2026-03-24 07:30:18.612999+00	1	Coach - Srijan Pradhan	2	[{"changed": {"fields": ["Image"]}}]	14	1
73	2026-03-24 09:06:52.28507+00	9	Counter Attacking Masterclass - 2026-03-24 18:00:00	1	[{"added": {}}]	9	1
74	2026-03-24 09:07:21.442118+00	9	Counter Attacking Masterclass - 2026-03-24 18:00:00	2	[{"changed": {"fields": ["Is published", "Is cancelled"]}}]	9	1
75	2026-03-25 08:14:22.901529+00	3	Coach - Sanjeev Shrestha	1	[{"added": {}}]	14	1
76	2026-03-25 08:19:54.074969+00	9	Counter Attacking Masterclass - 2026-03-24 18:00:00	2	[{"changed": {"fields": ["Location"]}}]	9	1
77	2026-03-25 08:21:00.451586+00	11	Goalkeeping Masterclass - 2026-12-01 06:00:00	1	[{"added": {}}]	9	1
78	2026-03-25 09:06:08.38839+00	28	Player - Ivor Fernandez	1	[{"added": {}}]	7	1
79	2026-04-01 15:50:00.637904+00	1	Training Photos	1	[{"added": {}}]	16	1
80	2026-04-01 15:50:18.044092+00	1	Training Photos — photo #1	1	[{"added": {}}]	17	1
81	2026-04-01 15:51:46.998275+00	2	Training Videos	1	[{"added": {}}]	16	1
82	2026-04-01 15:52:57.878016+00	2	Training Videos — video #2	1	[{"added": {}}]	17	1
83	2026-04-01 16:07:01.059597+00	3	Training Videos — video #3	1	[{"added": {}}]	17	1
84	2026-04-02 06:29:55.984961+00	2	Training Videos — video #2	2	[{"changed": {"fields": ["Thumbnail"]}}]	17	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	playerprofile
7	accounts	user
8	training	trainingprogram
9	training	trainingsession
10	bookings	booking
11	contents	coach
12	enquiries	enquiry
13	contents	testimonial
14	accounts	coachprofile
15	adminpanel	notification
16	gallery	gallerycategory
17	gallery	galleryitem
18	bookings	payment
19	adminpanel	auditlog
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-08 19:25:08.114759+00
2	contenttypes	0002_remove_content_type_name	2026-03-08 19:25:08.121413+00
3	auth	0001_initial	2026-03-08 19:25:08.169215+00
4	auth	0002_alter_permission_name_max_length	2026-03-08 19:25:08.174211+00
5	auth	0003_alter_user_email_max_length	2026-03-08 19:25:08.178479+00
6	auth	0004_alter_user_username_opts	2026-03-08 19:25:08.18322+00
7	auth	0005_alter_user_last_login_null	2026-03-08 19:25:08.188232+00
8	auth	0006_require_contenttypes_0002	2026-03-08 19:25:08.19055+00
9	auth	0007_alter_validators_add_error_messages	2026-03-08 19:25:08.196435+00
10	auth	0008_alter_user_username_max_length	2026-03-08 19:25:08.201701+00
11	auth	0009_alter_user_last_name_max_length	2026-03-08 19:25:08.206336+00
12	auth	0010_alter_group_name_max_length	2026-03-08 19:25:08.21242+00
13	auth	0011_update_proxy_permissions	2026-03-08 19:25:08.217683+00
14	auth	0012_alter_user_first_name_max_length	2026-03-08 19:25:08.222211+00
15	accounts	0001_initial	2026-03-08 19:25:08.284538+00
16	admin	0001_initial	2026-03-08 19:25:08.308768+00
17	admin	0002_logentry_remove_auto_add	2026-03-08 19:25:08.315803+00
18	admin	0003_logentry_add_action_flag_choices	2026-03-08 19:25:08.324388+00
19	training	0001_initial	2026-03-08 19:25:08.360838+00
20	bookings	0001_initial	2026-03-08 19:25:08.386404+00
21	sessions	0001_initial	2026-03-08 19:25:08.403836+00
22	accounts	0002_playerprofile_created_at_playerprofile_updated_at	2026-03-09 07:14:11.84901+00
23	training	0002_alter_trainingprogram_options_and_more	2026-03-09 07:14:11.896855+00
24	bookings	0002_alter_booking_options_alter_booking_unique_together_and_more	2026-03-09 07:14:11.963208+00
25	contents	0001_initial	2026-03-11 08:06:22.289243+00
26	accounts	0003_playerprofile_image	2026-03-11 08:39:34.331429+00
27	training	0003_alter_trainingprogram_options_and_more	2026-03-11 10:00:01.658807+00
28	training	0004_alter_trainingprogram_slug	2026-03-11 10:05:49.623611+00
29	training	0005_trainingsession_hero_image	2026-03-11 10:24:18.201181+00
30	enquiries	0001_initial	2026-03-12 10:43:09.842469+00
31	contents	0002_testimonial	2026-03-12 11:02:03.876331+00
32	enquiries	0002_alter_enquiry_options_enquiry_admin_notes_and_more	2026-03-12 11:20:04.25561+00
33	training	0006_alter_trainingsession_end_time_and_more	2026-03-15 18:16:18.147105+00
34	accounts	0004_coachprofile	2026-03-24 06:16:20.430722+00
35	contents	0003_delete_coach	2026-03-24 06:16:20.440052+00
36	adminpanel	0001_initial	2026-04-01 14:23:41.481718+00
37	gallery	0001_initial	2026-04-01 15:49:27.397643+00
38	gallery	0002_galleryitem_video_file	2026-04-01 16:05:45.624077+00
39	accounts	0005_user_is_email_verified	2026-04-04 19:41:43.043749+00
40	bookings	0003_add_payment_model	2026-04-05 19:29:13.103517+00
41	accounts	0006_coachprofile_availability_schedule_and_more	2026-04-06 05:31:35.418281+00
42	adminpanel	0002_notification_recipient_user	2026-04-06 05:31:35.455381+00
43	bookings	0004_booking_cancellation_reason	2026-04-06 05:31:35.469985+00
44	bookings	0005_alter_booking_cancellation_reason	2026-04-06 05:48:28.998628+00
45	accounts	0007_alter_playerprofile_emergency_contact_phone_and_more	2026-04-06 08:54:55.289458+00
46	enquiries	0003_alter_enquiry_phone	2026-04-06 08:54:55.29798+00
47	adminpanel	0003_auditlog	2026-04-07 06:28:21.535293+00
48	accounts	0008_user_deleted_at	2026-04-07 10:41:04.515126+00
49	training	0007_trainingprogram_deleted_at_and_more	2026-04-07 10:41:04.592269+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
wqq84udg2n6m358gyz8a6rd2e5vi4vp9	.eJxVjEEOwiAQRe_C2hCgQMGle89AZoZBqoYmpV0Z765NutDtf-_9l0iwrTVtnZc0ZXEWWpx-NwR6cNtBvkO7zZLmti4Tyl2RB-3yOmd-Xg7376BCr996CEUV7VhTJG-tsahVUBRGcpjRsRmDAfbBk2cAMoOJVoG2AW0mVaJ4fwDZBTfI:1w34no:C1V-7_VfvHJpEUts6I7LC4a2RT9VYvq4biZhJ6HTS80	2026-04-02 04:16:08.488419+00
fzott5t0l7rqhri4rkdap9brda73rxqk	.eJxVjEEOwiAQRe_C2hCgQMGle89AZoZBqoYmpV0Z765NutDtf-_9l0iwrTVtnZc0ZXEWWpx-NwR6cNtBvkO7zZLmti4Tyl2RB-3yOmd-Xg7376BCr996CEUV7VhTJG-tsahVUBRGcpjRsRmDAfbBk2cAMoOJVoG2AW0mVaJ4fwDZBTfI:1w3WWN:57aKgTTXSwkrVEEDtlPJeqdOaSBf8HCGK_HUsLo9Vw0	2026-04-03 09:51:59.403738+00
3jzmxw5dy4som18hw9mrszxznu6cxzaw	.eJxVjDsOwjAQBe_iGlnZ-INDSc8ZrN2sFweQLcVJhbg7iZQC2pl5760irkuOa0tznFhdFKjTLyMcn6nsgh9Y7lWPtSzzRHpP9GGbvlVOr-vR_h1kbHlbC3vjrZDtyQYeBIO41EEHQuCMBQ89IiYaWAY20J3duCExJoD3QkZ9vuuBN8U:1w9TA7:JFBqhwgHb_gWUuKHtQUXJOePvBZSegN2sjpvlu2zaC4	2026-04-19 19:29:35.666308+00
\.


--
-- Data for Name: enquiries_enquiry; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.enquiries_enquiry (id, name, email, phone, message, created_at, program_id, admin_notes, status) FROM stdin;
1	Parent One	parent1@gmail.com	9875132168	i want to know about your fees	2026-03-12 10:44:06.826934+00	2		contacted
2	Srijan Pradhan	srijan@example.com	9801234567	I want to know if there are one-to-one sessions for adults.	2026-03-12 10:48:14.818764+00	\N		contacted
38	Keaton Burt	wofahupo@mailinator.com	+1 (643) 183-4107	Nisi quas quo nostru	2026-03-19 09:48:16.020463+00	3		contacted
36	Olympia Rhodes	qavazy@mailinator.com	+1 (305) 461-6364	Consequatur recusand	2026-03-19 09:45:12.324426+00	\N		contacted
37	Xenos Cervantes	veto@mailinator.com	+1 (131) 861-2427	Molestias molestias	2026-03-19 09:45:30.856412+00	\N		contacted
39	Ishmael Rutledge	qyjadeqoty@mailinator.com	+1 (168) 187-4432	Quibusdam similique	2026-03-19 09:50:19.945433+00	\N		contacted
40	Abdul Stafford	zywinab@mailinator.com	+1 (381) 662-4257	In dignissimos minimIn dignissimos minimIn dignissimos minimIn dignissimos minimIn dignissimos minimIn dignissimos minim	2026-03-22 19:58:47.2035+00	2		contacted
3	Srijan Pradhan	pradhansrijan07@gmail.com	9861882503	i want to know something about your program	2026-03-18 10:45:35.701272+00	\N		contacted
41	Gabriel Willis	zucocewe@mailinator.com	+1 (705) 797-4831	Voluptas autem sit s	2026-04-01 09:40:23.275393+00	2		contacted
\.


--
-- Data for Name: gallery_gallerycategory; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.gallery_gallerycategory (id, name, slug, description, display_order, is_active, created_at) FROM stdin;
1	Training Photos	training-photos		0	t	2026-04-01 15:50:00.636891+00
2	Training Videos	training-videos		0	t	2026-04-01 15:51:46.997579+00
\.


--
-- Data for Name: gallery_galleryitem; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.gallery_galleryitem (id, media_type, image, video_url, thumbnail, caption, display_order, is_active, created_at, category_id, video_file) FROM stdin;
3	video		\N			0	t	2026-04-01 16:07:01.058246+00	2	gallery/videos/VID_20260203_234539304.mp4
2	video		https://www.youtube.com/watch?v=CIOhEcjMmWQ	gallery/thumbnails/1764736926.png		0	t	2026-04-01 15:52:57.876674+00	2	
1	photo	gallery/photos/kidss.jpg				0	t	2026-04-01 15:50:18.042887+00	1	
5	photo	gallery/photos/facebook_background_pic.webp			Facebook Background Picture	0	t	2026-04-07 08:27:52.717252+00	1	
9	video				comedy	0	t	2026-04-07 09:09:17.821393+00	2	gallery/videos/VID_20251006_103432861.mp4
\.


--
-- Data for Name: training_trainingprogram; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.training_trainingprogram (id, title, description, session_type, default_duration_minutes, default_price, is_active, created_at, display_order, hero_image, short_description, slug, deleted_at) FROM stdin;
2	Counter Attacking Masterclass	Counter attack	group	60	1000.00	t	2026-03-10 16:17:39.529073+00	0			counter-attacking-masterclass	\N
3	Goalkeeping Masterclass	Goal	one_to_one	60	1000.00	t	2026-03-11 17:36:02.876909+00	0		keeper	goalkeeping-masterclass	\N
7	Corner Kick Mastery	Fake Filler is a top browser extension for filling form fields, including descriptions, with random dummy data. Ideal for developers and testers, it automatically populates textareas and inputs using custom rules or random text generators. Popular alternatives include Fake Data and FakerFill.	group	60	499.99	t	2026-03-25 08:03:54.294111+00	1		Become an expert on scoring from different aspect from a corner kick.	corner-kick-mastery	\N
12	Sunt voluptate eum s	Enim quia voluptas e	group	47	177.00	f	2026-04-07 10:41:53.733806+00	79		Quaerat quis praesen	sunt-voluptate-eum-s	2026-04-07 10:42:13.234381+00
\.


--
-- Data for Name: training_trainingsession; Type: TABLE DATA; Schema: public; Owner: coaching_user
--

COPY public.training_trainingsession (id, session_date, start_time, end_time, location, max_players, price, is_published, is_cancelled, notes, created_at, coach_id, program_id, hero_image, deleted_at, is_active) FROM stdin;
12	2026-11-24	16:28:00	22:32:00	Est aut officia fugi	77	774.00	f	t	Libero dolore a culp	2026-03-25 08:21:56.00508+00	3	2		2026-04-07 10:48:47.927659+00	f
10	2026-12-20	06:00:00	07:00:00	Pokhara Rangasala	20	500.00	t	f		2026-03-25 08:18:22.089605+00	3	7		\N	t
13	2026-10-14	10:22:00	17:07:00	Aliquip nobis sint q	18	323.00	t	f	Officiis reprehender	2026-03-25 08:24:16.129778+00	8	2		\N	t
9	2027-03-24	18:00:00	20:00:00	pokhara	10	259.00	f	t	Vitae laborum tempor	2026-03-24 09:06:52.277761+00	8	2		2026-04-07 10:43:28.62231+00	f
\.


--
-- Name: accounts_coachprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.accounts_coachprofile_id_seq', 3, true);


--
-- Name: accounts_playerprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.accounts_playerprofile_id_seq', 36, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 42, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: adminpanel_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.adminpanel_auditlog_id_seq', 46, true);


--
-- Name: adminpanel_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.adminpanel_notification_id_seq', 43, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: bookings_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.bookings_booking_id_seq', 44, true);


--
-- Name: bookings_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.bookings_payment_id_seq', 10, true);


--
-- Name: contents_testimonial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.contents_testimonial_id_seq', 1, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 84, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 49, true);


--
-- Name: enquiries_enquiry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.enquiries_enquiry_id_seq', 45, true);


--
-- Name: gallery_gallerycategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.gallery_gallerycategory_id_seq', 2, true);


--
-- Name: gallery_galleryitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.gallery_galleryitem_id_seq', 10, true);


--
-- Name: training_trainingprogram_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.training_trainingprogram_id_seq', 12, true);


--
-- Name: training_trainingsession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: coaching_user
--

SELECT pg_catalog.setval('public.training_trainingsession_id_seq', 19, true);


--
-- Name: accounts_coachprofile accounts_coachprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_coachprofile
    ADD CONSTRAINT accounts_coachprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_coachprofile accounts_coachprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_coachprofile
    ADD CONSTRAINT accounts_coachprofile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_playerprofile accounts_playerprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_playerprofile
    ADD CONSTRAINT accounts_playerprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_playerprofile accounts_playerprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_playerprofile
    ADD CONSTRAINT accounts_playerprofile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: adminpanel_auditlog adminpanel_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.adminpanel_auditlog
    ADD CONSTRAINT adminpanel_auditlog_pkey PRIMARY KEY (id);


--
-- Name: adminpanel_notification adminpanel_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.adminpanel_notification
    ADD CONSTRAINT adminpanel_notification_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: bookings_booking bookings_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_pkey PRIMARY KEY (id);


--
-- Name: bookings_payment bookings_payment_booking_id_key; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_payment
    ADD CONSTRAINT bookings_payment_booking_id_key UNIQUE (booking_id);


--
-- Name: bookings_payment bookings_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_payment
    ADD CONSTRAINT bookings_payment_pkey PRIMARY KEY (id);


--
-- Name: contents_testimonial contents_testimonial_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.contents_testimonial
    ADD CONSTRAINT contents_testimonial_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: enquiries_enquiry enquiries_enquiry_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.enquiries_enquiry
    ADD CONSTRAINT enquiries_enquiry_pkey PRIMARY KEY (id);


--
-- Name: gallery_gallerycategory gallery_gallerycategory_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.gallery_gallerycategory
    ADD CONSTRAINT gallery_gallerycategory_pkey PRIMARY KEY (id);


--
-- Name: gallery_gallerycategory gallery_gallerycategory_slug_key; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.gallery_gallerycategory
    ADD CONSTRAINT gallery_gallerycategory_slug_key UNIQUE (slug);


--
-- Name: gallery_galleryitem gallery_galleryitem_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.gallery_galleryitem
    ADD CONSTRAINT gallery_galleryitem_pkey PRIMARY KEY (id);


--
-- Name: training_trainingprogram training_trainingprogram_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.training_trainingprogram
    ADD CONSTRAINT training_trainingprogram_pkey PRIMARY KEY (id);


--
-- Name: training_trainingprogram training_trainingprogram_slug_f0c75c8d_uniq; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.training_trainingprogram
    ADD CONSTRAINT training_trainingprogram_slug_f0c75c8d_uniq UNIQUE (slug);


--
-- Name: training_trainingsession training_trainingsession_pkey; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.training_trainingsession
    ADD CONSTRAINT training_trainingsession_pkey PRIMARY KEY (id);


--
-- Name: bookings_booking unique_player_session_booking; Type: CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT unique_player_session_booking UNIQUE (player_id, session_id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: adminpanel_auditlog_user_id_966f40ea; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX adminpanel_auditlog_user_id_966f40ea ON public.adminpanel_auditlog USING btree (user_id);


--
-- Name: adminpanel_notification_recipient_user_id_0f07533e; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX adminpanel_notification_recipient_user_id_0f07533e ON public.adminpanel_notification USING btree (recipient_user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: bookings_booking_player_id_65409cbe; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX bookings_booking_player_id_65409cbe ON public.bookings_booking USING btree (player_id);


--
-- Name: bookings_booking_session_id_d9183978; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX bookings_booking_session_id_d9183978 ON public.bookings_booking USING btree (session_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: enquiries_enquiry_program_id_fd8e99a2; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX enquiries_enquiry_program_id_fd8e99a2 ON public.enquiries_enquiry USING btree (program_id);


--
-- Name: gallery_gallerycategory_slug_a530a88f_like; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX gallery_gallerycategory_slug_a530a88f_like ON public.gallery_gallerycategory USING btree (slug varchar_pattern_ops);


--
-- Name: gallery_galleryitem_category_id_a021c609; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX gallery_galleryitem_category_id_a021c609 ON public.gallery_galleryitem USING btree (category_id);


--
-- Name: training_tr_is_publ_a72d9f_idx; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_tr_is_publ_a72d9f_idx ON public.training_trainingsession USING btree (is_published, is_cancelled);


--
-- Name: training_tr_session_9d8451_idx; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_tr_session_9d8451_idx ON public.training_trainingsession USING btree (session_date);


--
-- Name: training_trainingprogram_is_active_8254bdba; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_trainingprogram_is_active_8254bdba ON public.training_trainingprogram USING btree (is_active);


--
-- Name: training_trainingprogram_slug_f0c75c8d_like; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_trainingprogram_slug_f0c75c8d_like ON public.training_trainingprogram USING btree (slug varchar_pattern_ops);


--
-- Name: training_trainingsession_coach_id_965edc75; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_trainingsession_coach_id_965edc75 ON public.training_trainingsession USING btree (coach_id);


--
-- Name: training_trainingsession_is_active_eee4ab24; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_trainingsession_is_active_eee4ab24 ON public.training_trainingsession USING btree (is_active);


--
-- Name: training_trainingsession_program_id_a1b465f8; Type: INDEX; Schema: public; Owner: coaching_user
--

CREATE INDEX training_trainingsession_program_id_a1b465f8 ON public.training_trainingsession USING btree (program_id);


--
-- Name: accounts_coachprofile accounts_coachprofile_user_id_9eec5bec_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_coachprofile
    ADD CONSTRAINT accounts_coachprofile_user_id_9eec5bec_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_playerprofile accounts_playerprofile_user_id_8bc9eb5e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_playerprofile
    ADD CONSTRAINT accounts_playerprofile_user_id_8bc9eb5e_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: adminpanel_auditlog adminpanel_auditlog_user_id_966f40ea_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.adminpanel_auditlog
    ADD CONSTRAINT adminpanel_auditlog_user_id_966f40ea_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: adminpanel_notification adminpanel_notificat_recipient_user_id_0f07533e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.adminpanel_notification
    ADD CONSTRAINT adminpanel_notificat_recipient_user_id_0f07533e_fk_accounts_ FOREIGN KEY (recipient_user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_player_id_65409cbe_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_player_id_65409cbe_fk_accounts_ FOREIGN KEY (player_id) REFERENCES public.accounts_playerprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_session_id_d9183978_fk_training_; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_session_id_d9183978_fk_training_ FOREIGN KEY (session_id) REFERENCES public.training_trainingsession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_payment bookings_payment_booking_id_0afdaed6_fk_bookings_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.bookings_payment
    ADD CONSTRAINT bookings_payment_booking_id_0afdaed6_fk_bookings_booking_id FOREIGN KEY (booking_id) REFERENCES public.bookings_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: enquiries_enquiry enquiries_enquiry_program_id_fd8e99a2_fk_training_; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.enquiries_enquiry
    ADD CONSTRAINT enquiries_enquiry_program_id_fd8e99a2_fk_training_ FOREIGN KEY (program_id) REFERENCES public.training_trainingprogram(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: gallery_galleryitem gallery_galleryitem_category_id_a021c609_fk_gallery_g; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.gallery_galleryitem
    ADD CONSTRAINT gallery_galleryitem_category_id_a021c609_fk_gallery_g FOREIGN KEY (category_id) REFERENCES public.gallery_gallerycategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: training_trainingsession training_trainingses_program_id_a1b465f8_fk_training_; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.training_trainingsession
    ADD CONSTRAINT training_trainingses_program_id_a1b465f8_fk_training_ FOREIGN KEY (program_id) REFERENCES public.training_trainingprogram(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: training_trainingsession training_trainingsession_coach_id_965edc75_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: coaching_user
--

ALTER TABLE ONLY public.training_trainingsession
    ADD CONSTRAINT training_trainingsession_coach_id_965edc75_fk_accounts_user_id FOREIGN KEY (coach_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict xk3PRiDo3BdrsIqQPyk1RSVYhnSdqQ7BDUYomxQgBmtGwJKOAgWckJ3tmlCWdcp

