# Generated by Django 6.0.3 on 2026-04-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
