# Generated by Django 6.0.3 on 2026-03-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
