# Generated by Django 6.0.3 on 2026-04-06 07:32

import enquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_enquiry_options_enquiry_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=20, validators=[enquiries.models.validate_phone_number]),
        ),
    ]
