# Generated by Django 6.0.3 on 2026-03-09 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['session_date', 'start_time']},
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_training_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['session_date'], name='training_tr_session_9d8451_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['is_published', 'is_cancelled'], name='training_tr_is_publ_a72d9f_idx'),
        ),
    ]
