# Generated by Django 6.0.3 on 2026-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='training_programs/'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
