# Generated by Django 6.0.3 on 2026-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
