# Generated by Django 6.0.3 on 2026-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_trainingprogram_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='training_sessions/'),
        ),
    ]
