# Generated by Django 6.0.3 on 2026-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainingsession_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
