# Generated by Django 6.0.3 on 2026-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_trainingsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
